[package]
name = "trulience-db"
version.workspace = true
edition.workspace = true

[dependencies]
trulience-core = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
