[package]
name = "trulience-events"
version.workspace = true
edition.workspace = true

[dependencies]
trulience-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
